> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- Concatenate
- Random
- Transpose
- Vstack
- Hstack

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "gnspda/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/gnspda/numpy-array-operations


'https://jovian.ai/gnspda/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [5]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.concatenate  # (change this)
function2 = ???
function3 = ???
function4 = ???
function5 = ???

## Function 1 - np.concatenate

Add some explanation about the function in your own words

In [10]:
# Example 1 - working (change this)
arr1 = [[1, 2], 
        [3, 4]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1,  2,  5,  6,  7],
       [ 3,  4,  8,  9, 10]])

Explanation about example

In [12]:
# Example 2 - working
arr1 = [[1, 2,5], 
        [3, 4,8]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]


arr3 = [[5, 6, 65], 
        [8, 9, 14]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1,  2,  5,  5,  6,  7],
       [ 3,  4,  8,  8,  9, 10]])

Explanation about example

In [13]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

# dimension mismatch by 2 and 3 so, it only work in axis=1

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [14]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "gnspda/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/gnspda/numpy-array-operations


'https://jovian.ai/gnspda/numpy-array-operations'

## Function 2 - np.random.randint

Add some explanations

In [23]:
# Example 1 - working
# random.randint
a = np.random.randint(1,100)
a
#Gives random value between given numbers

86

Explanation about example

In [24]:
# Example 2 - working
a1 = np.random.randint(1,100,10)
a1
#Gives 10 random value between given numbers

array([80, 98, 45, 24, 48, 89, 12, 14, 47, 49])

Explanation about example

In [22]:
# Example 3 - breaking (to illustrate when it breaks)
a3 = np.random.randint(1,100,10,2)
a3
#It cant understand after range and number next intiger so we have to remove it

TypeError: Cannot interpret '2' as a data type

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [25]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "gnspda/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/gnspda/numpy-array-operations


'https://jovian.ai/gnspda/numpy-array-operations'

## Function 3 - np.transpose

Add some explanations

In [30]:
# Example 1 - working
b = [[1,2],
     [4,5]]
b1 = np.transpose(b)
b1
#b1 gives transpose of b

array([[1, 4],
       [2, 5]])

Explanation about example

In [31]:
# Example 2 - working
b2 = [[1,2,3],
     [4,5,6],
     [7,8,9]]
b3 = np.transpose(b)
b3
#b3 gives transpose of b2

array([[1, 4],
       [2, 5]])

Explanation about example

In [34]:
# Example 3 - breaking (to illustrate when it breaks)
b4 = [[1,2,3],
     [4,5,6],
     [7,8,9]]
b5 = np.transpose('b')
b5
#It cant read value mentioned in string

array('b', dtype='<U1')

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [35]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "gnspda/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/gnspda/numpy-array-operations


'https://jovian.ai/gnspda/numpy-array-operations'

## Function 3 - np.vstack

Add some explanations

In [37]:
# Example 1 - working
c=[[1,2],
  [3,4]]
c1=[[5,6],
   [7,8]]
c2=np.vstack((c, c1))
c2
#It combine both value if c and c1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Explanation about example

In [39]:
# Example 2 - working
c3=[[1,2,4],
  [3,4,6]]
c4=[[5,6,7],
   [7,8,8]]
c5=[[7,6,7],
   [7,9,8]]

c6=np.vstack((c3, c4, c5))
c6
#It combine both value if c3, c4, c5

array([[1, 2, 4],
       [3, 4, 6],
       [5, 6, 7],
       [7, 8, 8],
       [7, 6, 7],
       [7, 9, 8]])

Explanation about example

In [45]:
# Example 3 - breaking (to illustrate when it breaks)
c7=[[1,2,4],
  [3,4,6]]
c8=[[5,6,7],
   [7,8]]
c9=np.vstack((c7, c8))
c9
#Dimension shoud match in c7 and c8

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [46]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "gnspda/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/gnspda/numpy-array-operations


'https://jovian.ai/gnspda/numpy-array-operations'

## Function 4 - np.hstack

Add some explanations

In [48]:
# Example 1 - working
d=[[1,2],
  [3,4]]
d1=[[5,6],
   [7,8]]
d2=np.hstack((d, d1))
d2
#It combine both value if d and d1 horizontally

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Explanation about example

In [50]:
# Example 2 - working
# Example 2 - working
d3=[[1,2,4],
  [3,4,6]]
d4=[[5,6,7],
   [7,8,8]]
d5=[[7,6,7],
   [7,9,8]]

d6=np.hstack((d3, d4, d5))
d6
#It combine both value if d3, d4, d5 horizontally

array([[1, 2, 4, 5, 6, 7, 7, 6, 7],
       [3, 4, 6, 7, 8, 8, 7, 9, 8]])

Explanation about example

In [51]:
# Example 3 - breaking (to illustrate when it breaks)
d7=[[1,2,4],
  [3,4,6]]
d8=[[5,6,7],
   [7,8]]
d9=np.hstack((d7, d8))
d9
#Dimension shoud match in d7 and d8

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [52]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "gnspda/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/gnspda/numpy-array-operations


'https://jovian.ai/gnspda/numpy-array-operations'

## Function 5 - transpose

Add some explanations

In [53]:
# Example 1 - working
# Example 1 - working
b = [[1,2],
     [4,5]]
b1 = np.transpose(b)
b1
#b1 gives transpose of b

array([[1, 4],
       [2, 5]])

Explanation about example

In [54]:
# Example 2 - working
b2 = [[1,2,3],
     [4,5,6],
     [7,8,9]]
b3 = np.transpose(b)
b3
#b3 gives transpose of b2

array([[1, 4],
       [2, 5]])

Explanation about example

In [55]:
# Example 3 - breaking (to illustrate when it breaks)
b4 = [[1,2,3],
     [4,5,6],
     [7,8,9]]
b5 = np.transpose('b')
b5
#It cant read value mentioned in string

array('b', dtype='<U1')

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [59]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "gnspda/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/gnspda/numpy-array-operations


'https://jovian.ai/gnspda/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [60]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "gnspda/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/gnspda/numpy-array-operations


'https://jovian.ai/gnspda/numpy-array-operations'

In [ ]:
jovian.submit(assignment="zero-to-pandas-a2")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
